### ISSUE TITLE
java.lang.IllegalArgumentException: No implementation of method

### ISSUE THREAD

**Issue by llistochek** [obivan/fiaser#1]
При попытке запустить jar файл из релизов или файл, собранный из исходников, получаю следующую ошибку:
```
Exception in thread "main" java.lang.IllegalArgumentException: No implementation of method: :as-file of protocol: #'clojure.java.io/Coercions found for class: clojure.lang.Symbol
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
	at clojure.java.io$fn__11366$G__11348__11371.invoke(io.clj:35)
	at clojure.java.io$file.invokeStatic(io.clj:424)
	at clojure.java.io$file.invoke(io.clj:418)
	at fiaser.convert$fias_files.invokeStatic(convert.clj:21)
	at fiaser.convert$fias_files.invoke(convert.clj:12)
	at fiaser.convert$xml_dir_map.invokeStatic(convert.clj:28)
	at fiaser.convert$xml_dir_map.invoke(convert.clj:25)
	at fiaser.convert$processing_scope.invokeStatic(convert.clj:43)
	at fiaser.convert$processing_scope.invoke(convert.clj:40)
	at fiaser.convert$proceed_data.invokeStatic(convert.clj:100)
	at fiaser.convert$proceed_data.invoke(convert.clj:97)
	at fiaser.core$_main.invokeStatic(core.clj:27)
	at fiaser.core$_main.doInvoke(core.clj:20)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at fiaser.core.main(Unknown Source)
```
Вот конфиг файл:
```
{:sources {:xml-dir ./gar
           :xsd-dir ./gar_schemas}
:targets {:sqlite {:enabled? true
                   :file ./fias.db}
          :postgres {:enabled? false}}}
```
Проверил на openjdk-17, openjdk-11, openjdk-8

**Comment by obivan** [comment]
Похоже дело в том, что пути в конфиг-файле не заключены в кавычки. Попробуйте такую конфигурацию:
```
{:sources {:xml-dir "./gar"
           :xsd-dir "./gar_schemas"}

 :targets {:sqlite {:enabled? true
                    :file "./fias.db"}
           :postgres {:enabled? true}}}
```
